server:
  port: 8765

spring:
  application:
    name: caderneta-gateway

eureka:
  client:
    service-url:
      #defaultZone: http://netflix-eureka-server:8761/eureka #Esta url aponta para o container docker
      defaultZone: ${URL_EUREKA_SERVER:http://localhost:8761/eureka}
      
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitive-headers: Cookie,Set-Cookie
  routes:
    contas:
      service-id: caderneta-contas
      path: /ms-contas/**
    dashboard:
      service-id: caderneta-dashboard
      path: /ms-dashboard/**
    user:
      service-id: caderneta-user
      path: /ms-user/**
    stream:
      service-id: caderneta-stream
      path: /ms-stream/**
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000